version: 2
jobs:
  build:
    macos:
      xcode: "9.4.0"
    steps:
      - checkout
      - run:
          name: Install
          command: |
            brew install docker docker-machine docker-machine-driver-xhyve
      - run:
          name: Setup docker
          command: |
            set -x
            # boot2docker v18.09.0 results in errors
            STABLE_BOOT2DOCKER_URL="https://github.com/boot2docker/boot2docker/releases/download/v18.06.1-ce/boot2docker.iso"
            # docker-machine-driver-xhyve needs root owner and uid
            sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
            sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
            docker-machine --debug create --driver xhyve --virtualbox-boot2docker-url=$STABLE_BOOT2DOCKER_URL default
            eval "$(docker-machine env default)"
      - run:
          name: Test docker environment setup by running some test commands
          command: |
            docker-machine start default
            eval "$(docker-machine env default)"
            docker run appropriate/curl --retry 10 --retry-connrefused https://www.circleci.com
workflows:
  version: 2
  build-workflow:
    jobs:
      - build